In [9]:
import pandas as pd
import numpy as np
import datetime
import utils
import os
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=RuntimeWarning)

In [10]:

def add_features(events, features, on='id', how = 'left'):
    """Hace un merge de features a events"""
    return pd.merge(events, features, on=on, how = how)

def merge_features(list):
    feature_final = list[0]
    list.pop(0)
    for features in list:
        feature_final = add_features(feature_final,features)
    return feature_final

In [11]:
%run ./features_ambientes-ROB.ipynb
%run ./features_amenities-ROB.ipynb
%run ./features_metros-ROB.ipynb
%run ./features_descripcion_ROB.ipynb
%run ./features_direccion-ROB.ipynb
%run ./features_idzona-ROB.ipynb
%run ./features_publicacion-ROB.ipynb
%run ./features_basicos.ipynb
%run ./features_ambientes.ipynb
%run ./features_amenities.ipynb
%run ./features_metros.ipynb
%run ./features_descripcion.ipynb
%run ./features_direccion.ipynb

<class 'pandas.core.frame.DataFrame'>
Int64Index: 300000 entries, 0 to 59999
Data columns (total 23 columns):
antiguedad                    245731 non-null float64
banos                         267225 non-null float64
centroscomercialescercanos    300000 non-null float64
ciudad                        299545 non-null object
descripcion                   297980 non-null object
direccion                     233737 non-null object
escuelascercanas              300000 non-null float64
fecha                         300000 non-null object
garages                       252912 non-null float64
gimnasio                      300000 non-null float64
habitaciones                  271901 non-null float64
id                            300000 non-null int64
idzona                        264200 non-null float64
lat                           145817 non-null float64
lng                           145817 non-null float64
metroscubiertos               278301 non-null float64
metrostotales                 235878 non-null float64
piscina                       300000 non-null float64
precio                        240000 non-null float64
provincia                     299803 non-null object
tipodepropiedad               299947 non-null object
titulo                        293235 non-null object
usosmultiples                 300000 non-null float64
dtypes: float64(15), int64(1), object(7)
memory usage: 54.9+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 300000 entries, 0 to 59999
Data columns (total 23 columns):
antiguedad                    245731 non-null float64
banos                         267225 non-null float64
centroscomercialescercanos    300000 non-null float64
ciudad                        299545 non-null object
descripcion                   297980 non-null object
direccion                     233737 non-null object
escuelascercanas              300000 non-null float64
fecha                         300000 non-null datetime64[ns]
garages                       252912 non-null float64
gimnasio                      300000 non-null float64
habitaciones                  271901 non-null float64
id                            300000 non-null int64
idzona                        264200 non-null float64
lat                           145817 non-null float64
lng                           145817 non-null float64
metroscubiertos               278301 non-null float64
metrostotales                 235878 non-null float64
piscina                       300000 non-null float64
precio                        240000 non-null float64
provincia                     299803 non-null object
tipodepropiedad               299947 non-null object
titulo                        293235 non-null object
usosmultiples                 300000 non-null float64
dtypes: datetime64[ns](1), float64(15), int64(1), object(6)
memory usage: 54.9+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 300000 entries, 0 to 59999
Data columns (total 8 columns):
id                  300000 non-null int64
tipodepropiedad     299947 non-null object
gimnasio            300000 non-null float64
usosmultiples       300000 non-null float64
piscina             300000 non-null float64
garages             252912 non-null float64
escuelascercanas    300000 non-null float64
usosmultiples       300000 non-null float64
dtypes: float64(6), int64(1), object(1)
memory usage: 20.6+ MB
False
True
<class 'pandas.core.frame.DataFrame'>
Int64Index: 300000 entries, 0 to 59999
Data columns (total 23 columns):
antiguedad                    245731 non-null float64
banos                         267225 non-null float64
centroscomercialescercanos    300000 non-null float64
ciudad                        299545 non-null object
descripcion                   297980 non-null object
direccion                     233737 non-null object
escuelascercanas              300000 non-null float64
fecha                         300000 non-null datetime64[ns]
garages                       252912 non-null float64
gimnasio                      300000 non-null float64
habitaciones                  271901 non-null float64
id                            300000 non-null int64
idzona                        264200 non-null float64
lat                           145817 non-null float64
lng                           145817 non-null float64
metroscubiertos               278301 non-null float64
metrostotales                 235878 non-null float64
piscina                       300000 non-null float64
precio                        240000 non-null float64
provincia                     299803 non-null object
tipodepropiedad               299947 non-null object
titulo                        293235 non-null object
usosmultiples                 300000 non-null float64
dtypes: datetime64[ns](1), float64(15), int64(1), object(6)
memory usage: 54.9+ MB

In [12]:
features_list = []
features_list.append(pd.read_csv('features_ambientes_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_amenities_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_descripcion_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_direccion_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_idzona_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_metros_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_fecha_antiguedad_ROB.csv', low_memory=False))
features_list.append(pd.read_csv('features_basicos.csv', low_memory=False))
features_list.append(pd.read_csv('features_ambientes.csv', low_memory=False))
features_list.append(pd.read_csv('features_amenities.csv', low_memory=False))
features_list.append(pd.read_csv('features_metros.csv', low_memory=False))
features_list.append(pd.read_csv('features_descripcion.csv', low_memory=False))
features_list.append(pd.read_csv('features_direccion.csv', low_memory=False))

In [13]:
features = merge_features(features_list)

features.fillna(value=0, inplace=True)
features.head()

,id,habitaciones_x,banos_x,Apartamento_x,Bodega comercial_x,Casa_x,Casa en condominio_x,Casa uso de suelo_x,Departamento Compartido_x,Desconocida,...,Quintana Roo,San luis Potosí,Sinaloa,Sonora,Tabasco,Tamaulipas,Tlaxcala,Veracruz,Yucatán,Zacatecas
0,254099,2.0,2.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,53461,3.0,2.0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,247984,3.0,2.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,209067,2.0,1.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,185997,2.0,1.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
## esto genera un csv final con todos los features para usar en el modelo
features = features.drop('fecha',axis=1)
features.to_csv('../modelos/data_set.csv', index=False)

In [18]:
features.shape

(300000, 191)

In [19]:
features.columns

Index(['id', 'habitaciones_x', 'banos_x', 'Apartamento_x',
       'Bodega comercial_x', 'Casa_x', 'Casa en condominio_x',
       'Casa uso de suelo_x', 'Departamento Compartido_x', 'Desconocida',
       ...
       'Quintana Roo', 'San luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco',
       'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas'],
      dtype='object', length=191)